const genres=[
    {id:'1',
    image:'/imggenres/indie.png',
    name:"Indie"},
    {id:'2',
    image:'/imggenres/rock.png',
    name:"Rock"},
    {id:'3',
    image:'/imggenres/folk.png',
    name:"Folk & Singer-Songwriter"},
    {id:'4',
    image:'/imggenres/metal.png',
    name:"Metal"},
    {id:'5',
    image:'/imggenres/pop.png',
    name:"Pop"},
    {id:'6',
    image:'/imggenres/dance.png',
    name:"Dance & EDM"},
    {id:'7',
    image:'/imggenres/mexican.png',
    name:"Mexican music"},
    {id:'8',
    image:'/imggenres/latin.png',
    name:"Latin music"},
    {id:'9',
    image:'/imggenres/rnb.png',
    name:"Rn'B"},
    {id:'10',
    image:'/imggenres/colombian.png',
    name:"Colombian"},
    {id:'11',
    image:'/imggenres/christian.png',
    name:"Christian music"},
    {id:'12',
    image:'/imggenres/electronic.png',
    name:"Electronic"},
    {id:'13',
    image:'/imggenres/blues.png',
    name:"Blues"},
    {id:'14',
    image:'/imggenres/brazilian.png',
    name:"Brazilian"},
    {id:'15',
    image:'/imggenres/tvgaming.png',
    name:"TV,Gaming & Movies"},
    {id:'16',
    image:'/imggenres/reggaeton.png',
    name:"Reggaeton"},
    {id:'17',
    image:'/imggenres/classical.png',
    name:"Classical"},
    {id:'18',
    image:'/imggenres/soul.png',
    name:"Soul & Funk"},
    {id:'19',
    image:'/imggenres/african.png',
    name:"African music"},
    {id:'20',
    image:'/imggenres/jazz.png',
    name:"Jazz"},
    {id:'21',
    image:'/imggenres/vallenato.png',
    name:"Vallenato"},
    {id:'22',
    image:'/imggenres/salsa.png',
    name:"Salsa"},
    {id:'23',
    image:'/imggenres/merengue.png',
    name:"Merengue"},
    {id:'24',
    image:'/imggenres/reggae.png',
    name:"Reggae"},
    {id:'25',
    image:'/imggenres/rap.png',
    name:"Rap"}

]
export default genres;